### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by cz-cube** [jup-ag/jupiter-swap-api-client#18]
```
    Updating crates.io index
error: failed to select a version for `blake3`.
    ... required by package `solana-program v1.18.0`
    ... which satisfies dependency `solana-program = "=1.18.0"` of package `solana-sdk v1.18.0`
    ... which satisfies dependency `solana-sdk = "=1.18.0"` of package `solana-account-decoder v1.18.0`
    ... which satisfies dependency `solana-account-decoder = "~1.18"` of package `jupiter-swap-api-client v0.1.0 (https://github.com/jup-ag/jupiter-swap-api-client.git#e3c162b9)`
    ... which satisfies git dependency `jupiter-swap-api-client` of package `...`
versions that meet the requirements `^1.5.0` (locked to 1.5.4) are: 1.5.4

the package `solana-program` depends on `blake3`, with features: `digest` but `blake3` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
```

Maybe upgrade Solana dependencies from `~1.18` to `2`?

**Comment by yogioioi414** [comment]
> ```
>     Updating crates.io index
> error: failed to select a version for `blake3`.
>     ... required by package `solana-program v1.18.0`
>     ... which satisfies dependency `solana-program = "=1.18.0"` of package `solana-sdk v1.18.0`
>     ... which satisfies dependency `solana-sdk = "=1.18.0"` of package `solana-account-decoder v1.18.0`
>     ... which satisfies dependency `solana-account-decoder = "~1.18"` of package `jupiter-swap-api-client v0.1.0 (https://github.com/jup-ag/jupiter-swap-api-client.git#e3c162b9)`
>     ... which satisfies git dependency `jupiter-swap-api-client` of package `...`
> versions that meet the requirements `^1.5.0` (locked to 1.5.4) are: 1.5.4
> 
> the package `solana-program` depends on `blake3`, with features: `digest` but `blake3` does not have these features.
>  It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
> ```
> 
> Maybe upgrade `solana-account-decoder` from `~1.18` to `2`?

have this problem too

**Comment by TaoSeekAI** [comment]
same issue how to fix it ?
